service: serverless-pdf-demo
frameworkVersion: "1.59.1"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs8.10
  region: us-east-1
  stage: dev
  profile: default
  # apiGateway:
  #  binaryMediaTypes: # Optional binary media types the API might return
  #    - 'application/pdf'

  package:
    individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-domain-manager
  - serverless-apigw-binary

custom:

  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: "yarn"

  serverless-offline:
    location: .webpack/service

  apigwBinary:
    types:           #list of mime-types
      - 'image/jpeg'
      - 'text/html'
      - 'application/pdf'
  # customDomain:
  #   domainName: labs.mianio.com
  #   basePath: api
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true

functions:
  give-me-the-pdf:
    handler: functions/pdf.generate
    timeout: 20
    events:
      - http:
          path: pdf
          method: get
          cors: true
          parameters:
            headers:
              Accept: "application/pdf"
